Pages/ImpattoMisure/IndexImpattoMisure.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SRA.Areas.Identity.Data;
using SRA.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SRA.Pages.ImpattoMisure
{
    [Authorize]
    public class IndexImpattoMisureModel : PageModel
    {
        private readonly SRAContext _context;
        private readonly UserManager<SRAUser> _userManager;
        private readonly IHttpContextAccessor _httpcontextaccessor;
        public List<VW_Impatto_Misura_Display> ImpattoMisure { get; set; } = new List<VW_Impatto_Misura_Display>();

        public class ChiaveValoreJSON
        {
            [Key]
            public string ID { get; set; }
            public string Nome { get; set; }

        }
        public IndexImpattoMisureModel(SRAContext context, UserManager<SRAUser> userManager, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _userManager = userManager;
            _httpcontextaccessor = httpContextAccessor;
        }
        public async Task OnGetAsync()
        {
            ImpattoMisure = await _context.VW_Impatto_Misure_Display.AsNoTracking().ToListAsync();
        }

        public PartialViewResult OnGetAggiungiModalePartial(Guid? idmisura, Guid? idapplicazione, Guid? idrischio)
        {
            var aggiungiimpattomisuramodel = new InputImpattoMisureModel(_context);
            if (idmisura.HasValue && idapplicazione.HasValue && idrischio.HasValue)
            {
                aggiungiimpattomisuramodel.ImpattoMisura = _context.ImpattoMisure.AsNoTracking().Where(a => a.IDMisura == idmisura & a.IDApplicazione ==  idapplicazione & a.IDRischio == idrischio)
                    .FirstOrDefault();
                var listaapplicazioni = _context.Applicazioni.Where(a => a.Stato != "Dismessa").OrderBy(n => n.Nome).ToList();

                aggiungiimpattomisuramodel.ListaApplicazioni = new List<SelectListItem>();

                foreach (var applicazione in listaapplicazioni)
                {
                    aggiungiimpattomisuramodel.ListaApplicazioni.Add(new SelectListItem(applicazione.Nome, applicazione.ID.ToString()));
                }
            }

            return new PartialViewResult
            {
                ViewName = "_InterfacciaModaleImpattoMisure",
                ViewData = new ViewDataDictionary<InputImpattoMisureModel>(ViewData, aggiungiimpattomisuramodel)
            };
        }


        public IActionResult OnGetApplicazioniRischi(string idrischio)
        {
            List<ChiaveValoreJSON> applicazionirischio = new List<ChiaveValoreJSON>();
            applicazionirischio = _context.VW_Applicazioni_Rischi_Display.Where(s => s.IDRischio.ToString() == idrischio).Select(s => new ChiaveValoreJSON
            {
                ID = s.IDApplicazione.ToString(),
                Nome = s.NomeApplicazione
            }).OrderBy(o => o.Nome).ToList();
            var json = new JsonResult(applicazionirischio);
            return json;
        }
        public async Task<IActionResult> OnPostAggModImpattoMisuraAsync(InputImpattoMisureModel model)
        {
            if (!ModelState.IsValid) 
            {
                return RedirectToPage();
            }

            var recordesistente = _context.ImpattoMisure
              .Where(i => i.IDApplicazione == model.ImpattoMisura.IDApplicazione & i.IDMisura == model.ImpattoMisura.IDMisura & i.IDRischio == model.ImpattoMisura.IDRischio)
              .Any();
            if (recordesistente)
            {
                _context.Update(model.ImpattoMisura);
            }
            else
            {
                _context.Add(model.ImpattoMisura);
            }
            _context.SaveChanges();
            

            return RedirectToPage();
        }

        }
}

Pages/ImpattoMisure/IndexImpattoMisure.cshtml
@page
@model SRA.Pages.ImpattoMisure.IndexImpattoMisureModel
@{
    ViewData["Title"] = "Index";

}
<h2>Elenco dell'impatto delle contromisure su rischi e applicazioni </h2>
<br /> 
<p>
    <button type="button" class="bottone bottone1" data-toggle="ajax-modal-aggimpattomisura">
        Aggiungi
    </button>
</p>
<table id="tblimpattomisure" class="display table table-hover table-striped table-bordered table-sm">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ImpattoMisure[0].NomeMisura)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImpattoMisure[0].NomeApplicazione)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImpattoMisure[0].NomeRischio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImpattoMisure[0].Motivazione)
            </th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ImpattoMisure)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NomeMisura)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NomeApplicazione)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NomeRischio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Motivazione)
                </td>
                <td></td>
                <td>
                    <button type="button" class="bottone bottone1" data-toggle="ajax-modal-modimpattomisura" data-idmisura="@item.IDMisura" data-idapplicazione="@item.IDApplicazione" data-idrischio="@item.IDRischio">
                        Modifica
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>

<!-- Modal placeholder -->
<div id="modal-placeholder-impattomisure"></div>


@section Scripts {
    <script>

                        $(document).ready(function () {
                            $('#tblimpattomisure').DataTable({
                                // Opzioni di configurazione
                                paging: false,          // Abilita la paginazione
                                searching: true,       // Abilita la ricerca
                                ordering: true,        // Abilita l'ordinamento delle colonne
                            }
                            );
                        });

        $(function () {
            var placeholderElement = $('#modal-placeholder-impattomisure');
            $('button[data-toggle="ajax-modal-aggimpattomisura"]').click(function (event) {
                var geturl = `${window.location.protocol}//${window.location.hostname}${window.location.port ? `:${window.location.port}` : ''}`;
                var urldettaglio = '/ImpattoMisure/IndexImpattoMisure?handler=AggiungiModalePartial';
                geturl += urldettaglio;

                $.get(geturl).done(function (data) {
                    // append HTML to document, find modal and show it
                    //$(document.body).append(data).find('.modal').modal('show');
                    placeholderElement.html(data);
                    // const modal = document.getElementById('modal');
                    // modal.removeAttribute('aria-hidden');
                    // modal.setAttribute('inert', 'false');
                    // modal.querySelector('input, button, select, textarea').focus();
                    placeholderElement.find('.modal').modal('show');
                });
            });
        });

        $(function () {
            var placeholderElement = $('#modal-placeholder-impattomisure');
            $('button[data-toggle="ajax-modal-modimpattomisura"]').click(function (event) {
                var geturl = `${window.location.protocol}//${window.location.hostname}${window.location.port ? `:${window.location.port}` : ''}`;
                var urldettaglio = '/ImpattoMisure/IndexImpattoMisure?handler=AggiungiModalePartial';
                geturl += urldettaglio;
                        const idmisura = $(this).attr('data-idmisura');
                        const idapplicazione = $(this).attr('data-idapplicazione');
                        const idrischio = $(this).attr('data-idrischio');
                        geturl += "&idmisura=";
                geturl += idmisura;
                geturl += "&idapplicazione=";
                geturl += idapplicazione;
                geturl += "&idrischio=";
                geturl += idrischio;
                $.get(geturl).done(function (data) {
                    // append HTML to document, find modal and show it
                    //$(document.body).append(data).find('.modal').modal('show');
                    placeholderElement.html(data);
                    placeholderElement.find('.modal').modal('show');
                });
            });
        });
    </script>
}

Pages/ImpattoMisure/_InterfacciaModaleImpattoMisure.cshtml
@model SRA.Models.InputImpattoMisureModel
<!-- Modal -->
<div class="modal fade" id="mod-stato" tabindex="-1" role="dialog" aria-labelledby="addContactLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addContactLabel">Aggiungi/Modifica Impatto Misura</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                    
                </button>
            </div>


            <div class="modal-body">
                <form id="idnuovaImpattoMisura" asp-page-handler="AggModImpattoMisura" method="post">
                    Misura <br />
                    <select asp-for="@Model.ImpattoMisura.IDMisura" asp-items="@Model.ListaMisure" class="form-control"></select><br /><br /><br />
                    Rischio<br />
                    <select id="rischiomodal" asp-for="@Model.ImpattoMisura.IDRischio" asp-items="@Model.ListaRischi" class="form-control"></select><br /><br /><br />
                    Applicazione<br />
                    <select id="applicazionemodal" asp-for ="@Model.ImpattoMisura.IDApplicazione" asp-items="@Model.ListaApplicazioni" class="form-control"></select><br /><br /><br />
                    <br />
                    Motivazione<br />
                    <input asp-for="@Model.ImpattoMisura.Motivazione" class="form-control" />
                    <br />
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Chiudi</button>
                    <button type="submit" class="bottone bottone1" data-save="modal">Salva</button>
                </form>

            </div>
            <br />

            <div class="modal-footer">
            </div>

        </div>
    </div>
</div>

<script>
    $(function () {
        $("#rischiomodal").on("change", function () {
            var IDrischio = $(this).val();
            $("#applicazionemodal").empty();
            $("#applicazionemodal").append("<option value=''>Seleziona l'applicazione</option>");
            $.getJSON(`?handler=ApplicazioniRischi&idrischio=${IDrischio}`, (data) => {
                $.each(data, function (i, item) {
                    let opt = document.createElement("option");
                    opt.value = item.id; // the index
                    opt.innerHTML = item.nome;
                    $("#applicazionemodal").append(opt);

                });
            });
        })
    });
</script>