Pages/Applicazioni/IndexApplicazioni.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using SRA.Models;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.AspNetCore.Mvc.Rendering;
using SRA.Areas.Identity.Data;
using System.ComponentModel.DataAnnotations;

namespace SRA.Pages.Applicazioni
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly SRA.Models.SRAContext _context;
        public string FiltroNome { get; set; }
        public string FiltroStato { get; set; }
        public string FiltroTipoGestione { get; set; }
        public string FiltroTipoApplicazione { get; set; }
        [TempData] 
        public string Messaggio { get; set; }
        public string OrdinaNome { get; set; }
        public string OrdinaStato { get; set; }
        public string OrdinaData { get; set; }
        public string OrdinamentoCorrente { get; set; }
        public string FiltroCorrente { get; set; }

        public InputApplicazioneModel DatiModel { get; set; }
        private readonly UserManager<SRAUser> _userManager;
        private readonly IHttpContextAccessor _httpcontextaccessor;


        public IndexModel(SRA.Models.SRAContext context, UserManager<SRAUser> userManager, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _userManager = userManager;
            _httpcontextaccessor = httpContextAccessor;
        }

        public IList<Applicazione> Applicazioni { get; set; }

        //public ApplicazioneIndexData ApplicazioneVM { get; set; }

        public async Task OnGetAsync(string ordinamento)
        {
            
            CaricaDatiPagina();

        }

        public void CaricaDatiPagina()
        {
            //string[] valoriPossibili = { "nome_desc", "stato", "stato_desc", "data", "data_desc" };
            //if (!valoriPossibili.Contains(ordinamento))
            //{
            //    if (String.IsNullOrEmpty(ordinamento))
            //    {
            //        OrdinaNome = String.IsNullOrEmpty(ordinamento) ? "nome_desc" : "";
            //        OrdinaStato = ordinamento == "stato" ? "stato_desc" : "stato";
            //        OrdinaData = ordinamento == "data" ? "data_desc" : "data";
            //        OrdinamentoCorrente = ordinamento;

            //    }
            //    Applicazioni = _context.Applicazioni.OrderBy(N => N.Nome).Where(c => !c.Cancellato.Value || c.Cancellato == null)
            //    .ToList();
            //    return;
            //}
            
            DatiModel = new InputApplicazioneModel(_context);
            //ApplicazioneVM = new ApplicazioneIndexData();
            //ApplicazioneVM.ApplicazioniModEnum = await _context.Applicazioni
            Applicazioni = _context.Applicazioni.AsNoTracking().Where(c => !c.Cancellato.Value || c.Cancellato == null).OrderBy(N => N.Nome)
                .ToList();
            //OrdinaNome = String.IsNullOrEmpty(ordinamento) ? "nome_desc" : "";
            //OrdinaStato = ordinamento == "stato" ? "stato_desc" : "stato";
            //OrdinaData = ordinamento == "data" ? "data_desc" : "data";
            //OrdinamentoCorrente = ordinamento;
            //switch (ordinamento)
            //{
            //    case "nome_desc":
            //        Applicazioni = Applicazioni.OrderByDescending(n => n.Nome).ToList();
            //        break;
            //    case "stato":
            //        Applicazioni = Applicazioni.OrderBy(n => n.Stato).ToList();
            //        break;
            //    case "stato_desc":
            //        Applicazioni = Applicazioni.OrderByDescending(n => n.Stato).ToList();
            //        break;
            //    case "data":
            //        Applicazioni = Applicazioni.OrderBy(n => n.DataAvvio).ToList();
            //        break;
            //    case "data_desc":
            //        Applicazioni = Applicazioni.OrderByDescending(n => n.DataAvvio).ToList();
            //        break;
            //    default:
            //        Console.WriteLine("Numero non riconosciuto");
            //        break;
            //}
        }

        public PartialViewResult OnGetAggiungiModalePartial(Guid? idapplicazione)
        {
            var aggiungiapplicazionemodel = new InputApplicazioneModel(_context);
            if(idapplicazione.HasValue)
            {
                aggiungiapplicazionemodel.Applicazione = _context.Applicazioni.AsNoTracking().Where(a => a.ID == idapplicazione).FirstOrDefault();
            }

            return new PartialViewResult
            {
                ViewName = "_AggiungiApplicazione",
                ViewData = new ViewDataDictionary<InputApplicazioneModel>(ViewData, aggiungiapplicazionemodel)
            };
        }

        
        public IActionResult OnPostAggiungiApplicazione(InputApplicazioneModel model)
        {
            if (model.Applicazione.Stato == "Seleziona lo stato dell'applicazione") { model.Applicazione.Stato = null; }
            if (model.Applicazione.TipoApplicazione == "Seleziona il tipo di applicazione") { model.Applicazione.TipoApplicazione = null; }
            if (model.Applicazione.TipoGestione == "Seleziona il tipo di gestione") { model.Applicazione.TipoGestione = null; }
            if (model.Applicazione.ID.Equals(Guid.Empty))
            {
                _context.Add(model.Applicazione);
                _context.SaveChanges();

            }
            else 
                _context.Update(model.Applicazione);
            _context.SaveChanges();

            return RedirectToPage("./IndexApplicazioni");
        }

        public async Task<IActionResult> OnGetEliminaApplicazione(Guid idapplicazione)
        {
            var user = await _userManager.GetUserAsync(User).ConfigureAwait(false);
            try
            {
                Applicazione applicazionedacancellare = _context.Applicazioni.Where(i => i.ID == idapplicazione).FirstOrDefault();
                bool cancellabile = !(_context.Applicazioni_Rischi.AsNoTracking().Where(a => a.IDApplicazione == idapplicazione).Any()
                    || _context.Moduli.AsNoTracking().Where(m => m.IDApplicazione == idapplicazione).Any());
                if (applicazionedacancellare != null & cancellabile)
                {
                    applicazionedacancellare.Cancellato = true;
                    applicazionedacancellare.AutoreUltimaModifica = user.Nome + " " + user.Cognome;
                    applicazionedacancellare.DataUltimaModifica = DateTime.Now;
                    applicazionedacancellare.IPUltimaModifica = _httpcontextaccessor.HttpContext.Connection.RemoteIpAddress?.ToString();
                    _context.Update(applicazionedacancellare);
                    _context.SaveChanges();
                    Messaggio = "L'applicazione \"" + applicazionedacancellare.Nome + "\" è stata cancellata correttamente";
                }
                else
                {
                    Messaggio = "L'applicazione " + applicazionedacancellare.Nome + " non è cancellabile, sono presenti associazioni con moduli o rischi";
                }

            }
            catch (Exception ex)
            {

            }

            CaricaDatiPagina();

            return RedirectToPage("./IndexApplicazioni");
        }

    }
}

Pages/Applicazioni/IndexApplicazioni.cshtml
@page
@model SRA.Pages.Applicazioni.IndexModel


@{
    ViewData["Title"] = "Index";
}

<h2>Elenco delle Applicazioni</h2>

<div>
    <p style="color:red">@Model.Messaggio</p>
</div>
<p>
    <button type="button" class="bottone bottone1" data-toggle="ajax-modal-aggapplicazione">
        Aggiungi
    </button>
</p>
@*<table class="table table-hover table-striped table-bordered table-sm">*@
<table id="tblapplicazioni" class="display table table-hover table-striped table-bordered table-sm" style="width:100%">
    <thead>
        <tr>
            <th>
                <input type="text" placeholder="Filtra per Nome" />
            </th>
            <th>
                <input type="text" placeholder="Filtra per Stato" />
            </th>
            <th>
                
            </th>
            <th>
               
            </th>
            <th>
                <input type="text" placeholder="Filtra per Tipo Applicazione" />
            </th>
            <th>
                <input type="text" placeholder="Filtra per Tipo Gestione" />
            </th>
            <th></th>
            <th></th>
            <th></th>
        </tr>

        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Applicazioni[0].Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Applicazioni[0].Stato)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Applicazioni[0].DataAvvio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Applicazioni[0].DataDismissione)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Applicazioni[0].TipoApplicazione)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Applicazioni[0].TipoGestione)
            </th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Applicazioni)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Stato)
                </td>
                <td>
                   @Html.DisplayFor(modelItem => item.DataAvvio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataDismissione)
                </td>
                <td>
                   @Html.DisplayFor(modelItem => item.TipoApplicazione)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TipoGestione)
                </td>
                <td>
                    <a asp-page="../Moduli/IndexModuli" asp-route-idapplicazioneselezionata="@item.ID" class="bottone bottone1">Moduli</a>
                </td>
                <td>
                    <button type="button" class="bottone bottone1" data-toggle="ajax-modal-modapplicazione" data-idapplicazione="@item.ID">
                        Modifica
                    </button>
                </td>
                <td>
                    <form method="get">
                        <input type="hidden" name="handler" value="EliminaApplicazione" />
                        <input type="hidden" name="idapplicazione" value="@item.ID" />
                        <button id="elimina" type="submit" data-toggle="elimina" class="btn btn-danger">Elimina</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

<!-- Modal placeholder -->
<div id="modal-placeholder-applicazioni"></div>

@section Scripts {
    <script>
                $(function() {
            $('button[data-toggle="elimina"]').click(function(e) {
                var confirmed = confirm('Sei sicuro?');
                if (!confirmed) {
                    e.preventDefault(); // Annulla l'invio del modulo
                }
            });
        });

        

        $(document).ready(function () {
            var table = $('#tblapplicazioni').DataTable({
                // Opzioni di configurazione
                paging: false,          // Abilita la paginazione
                searching: true,       // Abilita la ricerca
                ordering: true,        // Abilita l'ordinamento delle colonne
                columnDefs: [
            { orderable: false, targets: [6, 7, 8] }, // Indici delle colonne da escludere dall'ordinamento
            { type: 'date-euro', targets: 2 }
        ]
            });

                // Impedisci la propagazione dell'evento di clic sugli input
        $('#tblapplicazioni thead tr:eq(0) input').on('click', function(event) {
            event.stopPropagation();
        });

            $('#tblapplicazioni thead tr:eq(0) input').on('keyup clear', function() {
            var colIndex = $(this).closest('th').index();
            //console.log('ColIndex:', colIndex, 'Value:', this.value); // Aggiungi un log per il debug
            table.column(colIndex).search(this.value).draw();
        });
        });



                $(function () {
            var placeholderElement = $('#modal-placeholder-applicazioni');
            $('button[data-toggle="ajax-modal-aggapplicazione"]').click(function (event) {
                var geturl = `${window.location.protocol}//${window.location.hostname}${window.location.port ? `:${window.location.port}` : ''}`;
                var urldettaglio = '/Applicazioni/IndexApplicazioni?handler=AggiungiModalePartial';
                geturl += urldettaglio;
                $.get(geturl).done(function (data) {
                    // append HTML to document, find modal and show it
                    //$(document.body).append(data).find('.modal').modal('show');
                    placeholderElement.html(data);
                    placeholderElement.find('.modal').modal('show');
                });
            });
        });

        $(function () {
            var placeholderElement = $('#modal-placeholder-applicazioni');
            $('button[data-toggle="ajax-modal-modapplicazione"]').click(function (event) {
                var geturl = `${window.location.protocol}//${window.location.hostname}${window.location.port ? `:${window.location.port}` : ''}`;
                var urldettaglio = '/Applicazioni/IndexApplicazioni?handler=AggiungiModalePartial';
                geturl += urldettaglio;
                const idapplicazione = $(this).attr('data-idapplicazione');
                geturl += "&idapplicazione=";
                geturl += idapplicazione;
                $.get(geturl).done(function (data) {
                    // append HTML to document, find modal and show it
                    //$(document.body).append(data).find('.modal').modal('show');
                    placeholderElement.html(data);
                    placeholderElement.find('.modal').modal('show');
                });
            });
        });

    </script>
}

Pages/Applicazioni/_AggiungiApplicazione.cshtml
@model SRA.Models.InputApplicazioneModel
<!-- Modal -->
<div class="modal fade" id="mod-stato" tabindex="-1" role="dialog" aria-labelledby="addContactLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addContactLabel">Aggiungi Applicazione</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                    
                </button>
            </div>


            <div class="modal-body">
                <form id="idnuovapplicazione" asp-page-handler="AggiungiApplicazione" method="post">
                    Nome <br />
                    <input asp-for="@Model.Applicazione.Nome" class="form-control" /> <br /> <br />
                    Stato Applicazione
                    <select id="statoapplicazione" asp-for="@Model.Applicazione.Stato" asp-items="@Model.ListaStatoApplicazione" class="form-control"></select><br />
                    Tipo Applicazione<br />
                    <select id="tipoapplicazione" asp-for="@Model.Applicazione.TipoApplicazione" asp-items="@Model.ListaTipoApplicazione" class="form-control"></select><br />
                     Tipo Gestione<br />
                    <select id="tipogestione" asp-for="@Model.Applicazione.TipoGestione" asp-items="@Model.ListaTipoGestione" class="form-control"></select><br />
                    Data Avvio<br />
                    <input asp-for="@Model.Applicazione.DataAvvio" class="form-control" />

                    <br />
                    <input type="hidden" asp-for="Applicazione.ID" value="@Model.Applicazione.ID" />
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Chiudi</button>
                    <button type="submit" class="bottone bottone1" data-save="modal">Salva</button>
                </form>
                
            </div>
            <br />
           
            <div class="modal-footer">
            </div>

        </div>
    </div>
</div>

<script>
    


</script>