Pages/DBMSs/IndexDBMSs.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.EntityFrameworkCore;
using SRA.Areas.Identity.Data;
using SRA.Models;

namespace SRA.Pages.DBMSs
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly SRA.Models.SRAContext _context;
        private readonly UserManager<SRAUser> _userManager;
        private readonly IHttpContextAccessor _httpcontextaccessor;
             
        public IndexModel(SRA.Models.SRAContext context, UserManager<SRAUser> userManager, IHttpContextAccessor httpcontextaccessor)
        {
            _context = context;
            _userManager = userManager;
            _httpcontextaccessor = httpcontextaccessor;
        }
        //public DBMSIndexData DBMS { get; set; }
        public int DBMSID { get; set; }

        public List<VW_DBMS_Display> DBMSs { get; set; } = new List<VW_DBMS_Display>();


        public async Task OnGetAsync(int? id)
        {
            DBMSs = await _context.VW_DBMSs_Display.AsNoTracking()
                .ToListAsync();
            //DBMS = new DBMSIndexData();
            //DBMS.DBMSsEnum = await _context.DBMSs
            //    .Include(m => m.Applicazione)
            //    .Include(m => m.DBMS_Basidati)
            //      .ThenInclude(m => m.Basedati)
            //     .AsNoTracking()
            //    .ToListAsync();
            //if (id != null)
            //{
            //    DBMSID = id.Value;
            //}

        }

        public PartialViewResult OnGetAggiungiModalePartial(Guid? iddbms)
        {
            var aggiungidbmsmodel = new InputDBMSsModel(_context);
            if (iddbms.HasValue)
            {
                aggiungidbmsmodel.DBMS = _context.DBMSs.AsNoTracking().Where(a => a.ID == iddbms).FirstOrDefault();
            }

            return new PartialViewResult
            {
                ViewName = "_InterfacciaModaleDBMSs",
                ViewData = new ViewDataDictionary<InputDBMSsModel>(ViewData, aggiungidbmsmodel)
            };
        }

        public async Task<IActionResult> OnPostAggModDBMSAsync(InputDBMSsModel model)
        {

            var user = await _userManager.GetUserAsync(User).ConfigureAwait(false);
            DBMS nuovadbms = new DBMS
            {
                Nome = model.DBMS.Nome,
                Versione = model.DBMS.Versione,
                IDProduttore = model.DBMS.IDProduttore

            };
            if (model.DBMS.ID.Equals(Guid.Empty))
            {
                
                nuovadbms.ID = Guid.NewGuid();
                try
                {
                    _context.Add(nuovadbms);
                    _context.SaveChanges();
                }
                catch (Exception ex)
                {

                }

            }
            else
            {
                nuovadbms.ID = model.DBMS.ID;
                try
                {
                    _context.Update(nuovadbms);
                    _context.SaveChanges();
                }
                catch (Exception ex)
                {

                }
            }

            return RedirectToPage("./IndexDBMSs");
        }
    }
}

Pages/DBMSs/IndexDBMSs.cshtml
@page
@model SRA.Pages.DBMSs.IndexModel


@{
    ViewData["Title"] = "Index";
}

<h2>Elenco Basi di dati</h2>

<p>
    <button type="button" class="bottone bottone1" data-toggle="ajax-modal-aggdbms">
        Aggiungi
    </button>
</p>
<table id="tbldbmss" class="display table table-hover table-striped table-bordered table-sm display" style="width:100%" ">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DBMSs[0].Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DBMSs[0].Versione)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DBMSs[0].Produttore)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.DBMSs)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.Versione)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Produttore)
                </td>
                <td>
                    <button type="button" class="bottone bottone1" data-toggle="ajax-modal-moddbms" data-iddbms="@item.ID">
                        Modifica
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>

<!-- Modal placeholder -->
<div id="modal-placeholder-dbmss"></div>


@section Scripts {
    <script>

        $(document).ready(function () {
            $('#tbldbmss').DataTable({
                // Opzioni di configurazione
                paging: false,          // Abilita la paginazione
                searching: true,       // Abilita la ricerca
                ordering: true
            }
            );
                // Definisci il tipo di ordinamento personalizzato
        $.fn.dataTable.ext.order['dom-checkbox'] = function(settings, col) {
            return this.api().column(col, {order: 'index'}).nodes().map(function(td, i) {
                return $(td).data('order');
            });
        };
        });


        $(function () {
            var placeholderElement = $('#modal-placeholder-dbmss');
            $('button[data-toggle="ajax-modal-aggdbms"]').click(function (event) {
                var geturl = `${window.location.protocol}//${window.location.hostname}${window.location.port ? `:${window.location.port}` : ''}`;
                var urldettaglio = '/DBMSs/IndexDBMSs?handler=AggiungiModalePartial';
                geturl += urldettaglio;

                $.get(geturl).done(function (data) {
                    // append HTML to document, find modal and show it
                    //$(document.body).append(data).find('.modal').modal('show');
                    placeholderElement.html(data);
                    placeholderElement.find('.modal').modal('show');
                });
            });
        });

        $(function () {
            var placeholderElement = $('#modal-placeholder-dbmss');
            $('button[data-toggle="ajax-modal-moddbms"]').click(function (event) {
                var geturl = `${window.location.protocol}//${window.location.hostname}${window.location.port ? `:${window.location.port}` : ''}`;
                var urldettaglio = '/DBMSs/IndexDBMSs?handler=AggiungiModalePartial';
                geturl += urldettaglio;
                const iddbms = $(this).attr('data-iddbms');
                geturl += "&iddbms=";
                geturl += iddbms;

                $.get(geturl).done(function (data) {
                    // append HTML to document, find modal and show it
                    //$(document.body).append(data).find('.modal').modal('show');
                    placeholderElement.html(data);
                    placeholderElement.find('.modal').modal('show');
                });
            });
        });

    </script>
}

Pages/DBMSs/_InterfacciaModaleDBMSs.cshtml
@model SRA.Models.InputDBMSsModel
<!-- Modal -->
<div class="modal fade" id="mod-stato" tabindex="-1" role="dialog" aria-labelledby="addContactLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addContactLabel">Aggiungi/Modifica Base di Dati</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                    
                </button>
            </div>


            <div class="modal-body">
                <form id="idnuovodbmss" asp-page-handler="AggModDBMS" method="post">
                    Nome <br />
                    <input asp-for="@Model.DBMS.Nome" class="form-control" />
                    <br />
                    Versione<br />
                    <input asp-for="@Model.DBMS.Versione" /> <br /><br />
                    Produttore<br />
                    <select id="produttore" asp-for="@Model.DBMS.IDProduttore" asp-items="@Model.ListaAziende" class="form-control"></select><br /><br />
                    <br />
                    <input type="hidden" asp-for="DBMS.ID" value="@Model.DBMS.ID" />
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Chiudi</button>
                    <button type="submit" class="bottone bottone1" data-save="modal">Salva</button>
                </form>

            </div>
            <br />

            <div class="modal-footer">
            </div>

        </div>
    </div>
</div>

<script>



</script>