Pages/TipiRischio/IndexTipiRischio.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.EntityFrameworkCore;
using SRA.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SRA.Pages.TipiRischio
{
    public class IndexTipiRischioModel : PageModel
    {
        private readonly SRAContext _context;
        public IndexTipiRischioModel(SRAContext context)
        {
            _context = context;
        }
        public List<TipoRischio> TipiRischio {  get; set; }
        public void OnGet()
        {
            TipiRischio = _context.TipiRischio.ToList();
        }

        public PartialViewResult OnGetAggiungiModalePartial(Guid? idtiporischio)
        {
            var aggiungitiporischiomodel = new InputTipiRischioModel();
            if (idtiporischio.HasValue)
            {
                aggiungitiporischiomodel.TipoRischio = _context.TipiRischio.AsNoTracking().Where(a => a.ID == idtiporischio).FirstOrDefault();
            }

            return new PartialViewResult
            {
                ViewName = "_InterfacciaModaleTipiRischio",
                ViewData = new ViewDataDictionary<InputTipiRischioModel>(ViewData, aggiungitiporischiomodel)
            };
        }

        public async Task<IActionResult> OnPostAggModTipoRischioAsync(InputTipiRischioModel model)
        {

            if (model.TipoRischio.ID.Equals(Guid.Empty))
            {
                _context.Add(model.TipoRischio);
                _context.SaveChanges();

            }
            else
            _context.Update(model.TipoRischio);
            _context.SaveChanges();

            return RedirectToPage("./IndexTipiRischio");
        }
    }
}

Pages/TipiRischio/IndexTipiRischio.cshtml
@page
@model SRA.Pages.TipiRischio.IndexTipiRischioModel
@{
    ViewData["Title"] = "Index";

}
<h2>Elenco delle Tipologie di Rischio</h2>

<p>
<button type="button" class="bottone bottone1" data-toggle="ajax-modal-aggtiporischio">
    Aggiungi
</button>
</p>
<table id="tbltipirischio" class="display table table-hover table-striped table-bordered table-sm">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TipiRischio[0].Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipiRischio[0].DescrizioneTipoRischio)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.TipiRischio)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DescrizioneTipoRischio)
                </td>
                <td>
                    <button type="button" class="bottone bottone1" data-toggle="ajax-modal-modtiporischio" data-idtiporischio="@item.ID">
                        Modifica
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>

<!-- Modal placeholder -->
<div id="modal-placeholder-tipirischio"></div>


@section Scripts {
    <script>

                $(document).ready(function () {
                    $('#tbltipirischio').DataTable({
                        // Opzioni di configurazione
                        paging: false,          // Abilita la paginazione
                        searching: true,       // Abilita la ricerca
                        ordering: true,        // Abilita l'ordinamento delle colonne
                    }
                    );
                });

$(function () {
    var placeholderElement = $('#modal-placeholder-tipirischio');
    $('button[data-toggle="ajax-modal-aggtiporischio"]').click(function (event) {
        var geturl = `${window.location.protocol}//${window.location.hostname}${window.location.port ? `:${window.location.port}` : ''}`;
        var urldettaglio = '/TipiRischio/IndexTipiRischio?handler=AggiungiModalePartial';
        geturl += urldettaglio;
        $.get(geturl).done(function (data) {
            // append HTML to document, find modal and show it
            //$(document.body).append(data).find('.modal').modal('show');
            placeholderElement.html(data);
            placeholderElement.find('.modal').modal('show');
        });
    });
});

$(function () {
    var placeholderElement = $('#modal-placeholder-tipirischio');
    $('button[data-toggle="ajax-modal-modtiporischio"]').click(function (event) {
        var geturl = `${window.location.protocol}//${window.location.hostname}${window.location.port ? `:${window.location.port}` : ''}`;
        var urldettaglio = '/TipiRischio/IndexTipiRischio?handler=AggiungiModalePartial';
        geturl += urldettaglio;
        const idtiporischio = $(this).attr('data-idtiporischio');
        geturl += "&idtiporischio=";
        geturl += idtiporischio;
        $.get(geturl).done(function (data) {
            // append HTML to document, find modal and show it
            //$(document.body).append(data).find('.modal').modal('show');
            placeholderElement.html(data);
            placeholderElement.find('.modal').modal('show');
        });
    });
});

</script>
}

Pages/TipiRischio/_InterfacciaModaleTipiRischio.cshtml
@model SRA.Models.InputTipiRischioModel
<!-- Modal -->
<div class="modal fade" id="mod-stato" tabindex="-1" role="dialog" aria-labelledby="addContactLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addContactLabel">Aggiungi/Modifica TipoRischio</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                    
                </button>
            </div>


            <div class="modal-body">
                <form id="idnuovarischio" asp-page-handler="AggModTipoRischio" method="post">
                    Nome Tipologi di Rischio<br />
                    <input asp-for="@Model.TipoRischio.Nome" class="form-control" />
                    <br />
                    Descrizione <br />
                    <input asp-for="@Model.TipoRischio.DescrizioneTipoRischio" class="form-control" />
                    <br />
                    <input type="hidden" asp-for="TipoRischio.ID" value="@Model.TipoRischio.ID" /><br /><br />
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Chiudi</button>
                    <button type="submit" class="bottone bottone1" data-save="modal">Salva</button>
                </form>

            </div>
            <br />

            <div class="modal-footer">
            </div>

        </div>
    </div>
</div>

<script>



</script>